---
#Step1: install many packages
- hosts: vagrant3
  become: yes
  tasks:
  - name: install basic environment
    yum: pkg={{ item }} state=latest
    with_items:
      - gcc
      - gcc-c++
      - autoconf
      - libjpeg 
      - libjpeg-devel
      - libpng
      - libpng-devel
      - freetype
      - freetype-devel
      - libxml2
      - libxml2-devel
      - zlib
      - zlib-devel
      - glibc
      - glibc-devel
      - glib2
      - glib2-devel 
      - bzip2
      - bzip2-devel
      - ncurses
      - ncurses-devel
      - curl
      - curl-devel
      - e2fsprogs
      - e2fsprogs-devel
      - krb5-server
      - krb5-devel
      - libidn
      - libidn-devel
      - openldap
      - openldap-devel
      - nss_ldap
      - openldap-clients
      - openldap-servers
      - net-snmp-devel
      - php-bcmath
      - net-tools
    tags:
      - basic
  - name: install apache environment
    yum: pkg={{ item }} state=latest
    with_items:
      - httpd
      - httpd-devel
    tags:
      - apache
  - name: install mysql environment
    yum: pkg={{ item }} state=latest
    with_items:
      - mysql 
      - mariadb-server
      - mysql-devel
    when: ansible_distribution_major_version == "7"
    tags:
      - mysql

  - name: install php environment
    yum: pkg={{ item }} state=latest
    with_items:
      - php
      - php-mysql 
      - php-common
      - php-gd
      - php-mbstring
#      - php-mcrypt
      - php-devel
      - php-xml
    tags:
      - php 
    notify:
      - restart mysql
      - restart apache

#  - name: add bcmath
#    command: yum install *bcmath* --skip-broken
#    tags:
#      - others
#    notify: 
#      - restart mysql
#      - restart apache

  handlers:
    - name: restart mysql
      service: name=mariadb state=restarted
    - name: restart apache
      service: name=httpd state=restarted

